name: Feature request
description: File a feature request
labels: enhancement
body:
  - type: textarea
    id: quick-summary
    attributes:
      label: Quick summary
      description: Please briefly describe what feature you would like J2ME Loader to have.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: Please describe the feature as accurately as possible.
    validations:
      required: false
